# Site
name: "Bao"
title: "Please Enjoy"
description: "Bao: Packed With Internet Flavor"
logo: 'assets/images/logo.gif'
favicon: 'assets/images/squarelogo.gif'
baseurl: 
google_analytics: 
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/
email: nim@wunnan.com

# Authors
authors:
  nim:
    name: nim
    display_name: Ním
    gravatar: ab98ebc87d939b6d2e0b8cede892af7d
    email: nim@wunnan.com
    web: http://wunnan.com
    twitter: https://twitter.com/nimwunnan
    description: "Artist and writer, founder and janitor of all things at paddleboat.online"
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
